In [3]:
import numpy as shiro
a=shiro.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as sivashiro
a=sivashiro.array([[1,2,3,4]])
print(a)

[[1 2 3 4]]


In [3]:
import numpy as sivashiro
a=sivashiro.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=sivashiro.zeros((3,4))
print("THE ELEMENT IN ARRAY IS",b)
c=sivashiro.full((3,3),7)
print(c)
d=sivashiro.random.random((3,4))
print(d)
e=sivashiro.array((3,3))
print(e)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
f=b.reshape(4,3)
print(f)
g=a.flatten()
print(g)
h=a.astype('f')
print(h)
print(a)
print(a[1:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
THE ELEMENT IN ARRAY IS [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.30303228 0.79158264 0.91507405 0.48640832]
 [0.40519508 0.28634869 0.58028049 0.15927479]
 [0.92563465 0.48326078 0.60129259 0.68840663]]
[3 3]
2
(3, 4)
12
int32
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[]
