In [3]:
import numpy as sivashiro2
arr=sivashiro2.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Orginal array:\n",arr)
print("\nEvery other rows:arr[0:3:2]:\n",arr[0:3:2])

Orginal array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

Every other rows:arr[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [4]:
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:arr[:2,:3]:\n",temp)


Array with first 2 rows and 3 columns:arr[:2,:3]:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [5]:
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1),""(3,0):\n",temp)


Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [6]:
cond=arr>2
temp=arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [8]:
arr=sivashiro2.array([1,2,3,4,5,6,7])
print("\nReturns every other elements in the array[::2]:",arr[::2])



Returns every other elements in the array[::2]: [1 3 5 7]


In [10]:
arr1=sivashiro2.array([1,2,3])
arr2=sivashiro2.array([4,5,6])
arr=sivashiro2.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\njoined array.\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

joined array.
 [1 2 3 4 5 6]


In [11]:
arr=sivashiro2.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)


Horizontal joining:
 [1 2 3 4 5 6]


In [13]:
arr=sivashiro2.vstack((arr1,arr2))
print("\nVertical joining:\n",arr)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [15]:
arr=sivashiro2.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [16]:
arr=sivashiro2.array([1,2,3,4,5,6])
newarr=sivashiro2.array_split(arr,3)
print("\nOrginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Orginal Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
print("\nSplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Splitted array in another form:

[1 2]
[3 4]
[5 6]
